name: OPA policies Coverage Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  opa-coverage-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up OPA and Run policy checks
        run: |
          # Install dependencies

          apt-get -y update; apt-get -y install curl
          curl --version
          curl -L https://openpolicyagent.org/downloads/v0.36.1/opa_linux_amd64_static -vvv --output /usr/bin/opa
          chmod +x /usr/bin/opa
          version=$(opa version)
          echo $version

          # Run OPA policy checks

          policies=$(find ./policy-as-code/OPA/policy -name "*.rego" | grep -v .utils. | cut -d"." -f2 | sort | uniq)
          for policy in ${policies}
          do
          printf "\nPolicy: \e[0;32m.${policy}.rego\e[0m\n"
          utils=$(find ./policy-as-code/OPA/policy -name "*.utils.*")
          target=".${policy}.* $utils"
          set -o pipefail
          opa test $target -v | grep -v ".utils." || exit 1
          coverage_values=`opa test --coverage $target -v | grep -iE '"coverage": [ 0-9 ]+'`
          coverage=`printf "${coverage_values}%%\n" | tail -n 1 | xargs`
          echo $coverage

          if [ "$coverage" != "coverage: 100%" ]; then
            opa test --coverage $target -v
            printf "\n\e[0;31mRule test coverage must be 100%%\e[0m\n"
            exit 1
          fi;
          done

