name: OPA policies Coverage Check
on:
  [push, pull_request]

jobs:
  opa-coverage-check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up OPA
        run: |
          curl -L -o opa https://github.com/open-policy-agent/opa/releases/latest/download/opa_linux_amd64
          chmod +x opa

      - name: Fetch OPA policies
        run: |
          git clone https://github.com/aws-samples/aws-infra-policy-as-code-with-terraform.git
          cp aws-infra-policy-as-code-with-terraform/policy-as-code/* .

      - name: Run OPA policy check
        run: |
          policies=$(find ./OPA/policy -name "*.rego" | grep -v .utils. | cut -d"." -f2 | sort | uniq)
          for policy in ${policies}
          do
          printf "\nPolicy: \e[0;32m.${policy}.rego\e[0m\n"
          utils=$(find ./OPA/policy -name "*.utils.*")
          target=".${policy}.* $utils"
          set -o pipefail
          opa test $target -v | grep -v ".utils." || exit 1
          coverage_values=`opa test --coverage $target -v | grep -iE '"coverage": [ 0-9 ]+'`
          coverage=`printf "${coverage_values}%%\n" | tail -n 1 | xargs`
          echo $coverage

          if [ "$coverage" != "coverage: 100%" ]; then
            opa test --coverage $target -v
            printf "\n\e[0;31mRule test coverage must be 100%%\e[0m\n"
            exit 1
          fi;
          done

